---
title: "Solutions for the Mock Practical"
author: "????"
date: "????"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[**Delete this line and other instructions within square brackets prior to "kniting" for your final submission**]

# Solutions to Q1


## 1.1

[**Add your R code here**]
```{r}
#????
```


## 1.2

[**Add your R code here**]
```{r}
#????
```


## 1.3

[**Add your R code here**]
```{r}
#????
```


## 1.4

[**Add your R code here**]
```{r}
#????
```

[**Give your comments here**]


## 1.5


### 1.5(a)

[**Give your explanation here**]


### 1.5(b)

The following R function takes a single argument `N` and returns a single realisation of $\tilde{p}_N$.
    
```{r}
imp=function(N){
    x <- 2/runif(N)
    return((1/N)*sum(x^2/(2*pi*(1+x^2))))
  }
```

[**Add your R code for `mcMany2` here**]
```{r}
#????
```


### 1.5(c)

[**Add your R code to run `mcMany2` here**]
```{r}
#????
```

[**Give your comments about the mean and variance here**]


# Solutions to Q2


## 2.1

[**Add your R code for `gammaT` here**]
```{r}
#????
```


## 2.2

Generate a (synthetic) data set by running the following R code:
```{r}
set.seed(3421)
data <- rgamma(100,2,0.5)
#Truncate anything bigger than 5
data[data>5] <- 5
data <- sort(data) #x=(x^o,x^c)
```

[**How many precise observations are there?**]

## 2.3

[**Complete this function by adding code for `m` and the `beta` and `z` updates**]
```{r}
gibbs = function(N,x,sstar)
{
 a <- 1; b <- 1 #prior hyper-parameters
 n <- length(x)
 m <- #WRITE YOUR SOLUTION
 x0 <- x[1:m] #observed survival times
 betaVec <- rep(0,N) #store beta samples here 
 zMat <- matrix(0,nrow=N,ncol=(n-m)) #sore z samples here
 #Initialise
 beta <- #WRITE YOUR SOLUTION
 z <- rep(sstar,n-m)
 betaVec[1] <- beta; zMat[1,] <- z
 for(i in 2:N)
 {
  #update beta 
  beta <- #WRITE YOUR SOLUTION
  #update z 
  z <- #WRITE YOUR SOLUTION
  #store
  betaVec[i] <- beta; zMat[i,] <- z
 }
 return(list(betaVec,zMat)) 
}
```


## 2.4

[**Add your R code to run your investigations here**]
```{r}
#????
```

[**Give your comments about your investigation here**]


# Solutions to Q3


## 3.1

[**Add your Stan model code here for M1.**]
```{{stan}}
data {
?????
}
parameters {
?????
}
model {
?????
}

```

[**Add your Stan model code here for M2.**]
```{{stan}}
data {
?????
}
parameters {
?????
}
model {
?????
}

```


## 3.2

[**Add your R code to sample from the posterior here**]
```{r, message=FALSE, results="hide"}
library(rstan)

# ????
```

[**Add your R code to approximate a 95% credible interval here**]
```{r, message=FALSE}
# ????
```


## 3.3

[**Add your R code for calculating pseudo-BMA weights here**]
```{r, message=FALSE}
library(loo)

# ????
```


# Solutions to Q4


## 4.1

[**Give the details of the fitted distribution here**]

[**Produce a plot of the fitted density**]
```{r, message=FALSE}
# ????
```


## 4.2

[**Load in the following data**]
```{r, message=FALSE}
class_ratios <- data.frame(region = c(rep(1,20),
                                      rep(2,10)),
                           district = c(rep(1,4),
                                        rep(2,8),
                                        rep(3,8),
                                        rep(1,4),
                                        rep(2,6)),
                           town = c(1:4,
                                    1:8,
                                    1:8,
                                    1:4,
                                    1:6),
                           ratio = c(15.89,18.10,22.08,20.72,11.83,18.25,
                                     18.60,21.64,29.84,16.58,28.75,38.96,
                                     11.19,11.36,16.01, 9.06,17.17,18.39,
                                     31.80,24.44,23.45,27.62,25.21,23.47,
                                     22.33,19.98,20.17,17.08,22.47,20.29))
```

[**Give your answer here**]


## 4.3

[**Add your Stan model code here.**]
```{{stan}}
data {
  int<lower=1> NK;                   // num regions
  int<lower=1> NJ[NK];               // num of districts per region
  int<lower=0> N;                    // num towns
  int<lower=1,upper=NK> region[N];   // town's region
  int<lower=1> district[N];          // town's district
  real<lower=0> R[N];                // observed ratios
}
transformed data {
  int<lower=1> max_districts; // max num of districts in a region
  
  max_districts = max(NJ);
}
parameters {
  ????
}
model {
  ????
}
```


## 4.4

[**Add your R code to sample from the posterior here**]
```{r, message=FALSE, results="hide"}
library(rstan)

#????
```

[**Add your R code to give the posterior means and standard deviations**]
```{r, message=FALSE}
# ????
```


## 4.5

[**Add your answers here**]
